# Generated by Django 4.0 on 2021-12-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sizes_remove_product_sizes_product_sizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
